# Change these first
owner: kilowatthk # Your GitHub organization or username, where this repository lives
repo: uptime-status # The name of this repository

sites:
  - name: Website
    url: https://www.kilowatt.hk
  - name: API
    url: $API_URL
  - name: OCPP
    url: $OCPP_URL
    
assignees: # Users to assign downtime issues (optional)
  - mkhmylife

status-website:
  cname: status.kilowatt.hk
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Kilowatt Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
